### ISSUE TITLE
ERROR   Unexpected internal error during analysis of gene family GF_000001

### ISSUE THREAD

**Issue by jwang147** [VIB-PSB/ksrates#52]
Hello, I get an error at the whole paranome Ks analysis like that, could you give me some advice? Thank you very much.
```
INFO    Paralog wgd analysis for species [Dede]
INFO    Mon Jul 10 17:18:26 2023
INFO    - - - - - - - - - - - - - - - - - - - -
INFO    Checking if sequence data files exist and if sequence IDs are compatible with wgd pipeline...
INFO    Completed
INFO    Creating directory [paralog_distributions/]
INFO    Running wgd paralog Ks pipeline...
INFO    ---
INFO    Checking external software...
INFO    makeblastdb: 2.11.0+
INFO    blastp: 2.11.0+
INFO    mcl 14-137
INFO    muscle 5.1.linux64 []
INFO    AAML in paml version 4.9j, February 2020
INFO    FastTree Version 2.1.11 Double precision (No SSE3)
INFO    Creating output directory /data/jwang/5-dendrobium_devonianum_genome/7.2.ksrates/paralog_distributions/wgd_Dede
INFO    Translating CDS file Dede.cds...
WARNING Sequence length != multiple of 3 for De_Chr06G000001.mRNA1!
WARNING Invalid codon  AG in De_Chr06G000001.mRNA1
WARNING There were 2 warnings during translation
INFO    ---
INFO    Running all versus all Blastp
INFO    Writing protein Blastdb sequences to /data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast_tmp/...
INFO    Writing protein query sequences to /data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast_tmp/...
INFO    Performing all versus all Blastp (this might take a while)...
INFO    Making Blastdb
INFO    makeblastdb -in /data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast_tmp/Dede.db.fasta -dbtype prot
INFO    makeblastdb output:
Building a new DB, current time: 07/10/2023 17:18:36
New DB name:   /data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast_tmp/Dede.db.fasta
New DB title:  /data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast_tmp/Dede.db.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 30408 sequences in 0.42232 seconds.
INFO    Running Blastp
INFO    blastp -db /data/jwang/5-dendrobium_devonianum_genome/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast_tmp/Dede.db.fasta -query /data/jwang/5-dendrobium_devonianum_genome/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast_tmp/Dede.query.fasta -evalue 1e-10 -outfmt 6 -num_threads 30 -out /data/jwang/5-dendrobium_devonianum_genome/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.blast.tsv
INFO    All versus all Blastp done
INFO    Removing tmp directory
INFO    ---
INFO    Running whole paranome Ks analysis...
WARNING Filtered out the 3 largest gene families because their size is > 200
WARNING If you want to analyse these large families anyhow, please raise the `max_gene_family_size` parameter
INFO    Started analysis of 4368 gene families in parallel using 30 threads
INFO    Performing analysis on gene family GF_000004 (size 159)
ERROR   Unexpected internal error during analysis of gene family GF_000004:
Traceback (most recent call last):
  File "/data/jwang/software/miniconda3/envs/ksrate/lib/python3.7/site-packages/wgd_ksrates/ks_distribution.py", line 280, in analyse_family_try_except
    n_families, is_last_family)
  File "/data/jwang/software/miniconda3/envs/ksrate/lib/python3.7/site-packages/wgd_ksrates/ks_distribution.py", line 371, in analyse_family
    msa_path, stats, successful = prepare_aln(msa_path_protein, nucleotide)
  File "/data/jwang/software/miniconda3/envs/ksrate/lib/python3.7/site-packages/wgd_ksrates/alignment.py", line 43, in prepare_aln
    with open(msa_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.ks_tmp/GF_000004.fasta.msa'
ERROR   Skipping gene family
INFO    Performing analysis on gene family GF_000005 (size 130)
ERROR   Unexpected internal error during analysis of gene family GF_000005:
Traceback (most recent call last):
  File "/data/jwang/software/miniconda3/envs/ksrate/lib/python3.7/site-packages/wgd_ksrates/ks_distribution.py", line 280, in analyse_family_try_except
    n_families, is_last_family)
  File "/data/jwang/software/miniconda3/envs/ksrate/lib/python3.7/site-packages/wgd_ksrates/ks_distribution.py", line 371, in analyse_family
    msa_path, stats, successful = prepare_aln(msa_path_protein, nucleotide)
  File "/data/jwang/software/miniconda3/envs/ksrate/lib/python3.7/site-packages/wgd_ksrates/alignment.py", line 43, in prepare_aln
    with open(msa_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.ks_tmp/GF_000005.fasta.msa'
.....
ERROR   Skipping gene family
ERROR   Too many gene family analyses failed, terminating threads...
ERROR   Too many gene family analyses failed, terminating threads...
ERROR   Too many gene family analyses failed, terminating threads...
ERROR   --
ERROR   The analyses of more than 1% of gene families [44/4368] have failed due to unexpected internal errors
```
I have suspected the issue with i-adhore, but it works normally.

/data/jwang/software/miniconda3/envs/ksrate/bin/i-adhore
Usage: /data/jwang/software/miniconda3/envs/ksrate/bin/i-adhore [configuration file]

**Comment by Cecilia-Sensalari** [comment]
Hi! Thanks for reaching out :)
The "core" error message is that it can't find the MSA file:
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/jwang/7.2.ksrates/paralog_distributions/wgd_Dede/Dede.ks_tmp/GF_000004.fasta.msa'
```
This might be caused by the fact that you're using a different version of BLAST and/or MUSCLE compared to the ones we used to develop ksrates: have a look at issue #48 and #41, respectively.

These are the versions you're currently using:
```
INFO    Checking external software...
INFO    makeblastdb: 2.11.0+
INFO    blastp: 2.11.0+
INFO    mcl 14-137
INFO    muscle 5.1.linux64 []
INFO    AAML in paml version 4.9j, February 2020
INFO    FastTree Version 2.1.11 Double precision (No SSE3)
```

You can try to downgrade MUSCLE from 5.1 to 3.8 and, if needed, use a more recent BLAST version (for example 2.5.0 or 2.6).

Hope this helps!

**Comment by Cecilia-Sensalari** [comment]
Hi, I'll now close this issue for inactivity, feel free to contact me again if needed!
